import sys
import os
from pathlib import Path
from datetime import date

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db.database import db_manager

# Complete list of 75 complete teacher profiles
TEACHERS_DATA = [
    # 1-50 from CSV, but with complete details (emergency contact, etc.) added
    {"employee_id": "EMP-2024-001", "full_name": "DR. MARIA SANTOS", "department": "Science Department", "position": "Department Head", "specialization": "Physics", "contact_number": "09171234567", "address": "123 Teacher Lane, Quezon City", "birth_date": "1985-03-15", "blood_type": "A+", "emergency_contact_name": "JUAN SANTOS", "emergency_contact_number": "09181234567"},
    {"employee_id": "EMP-2024-002", "full_name": "JUAN DELA CRUZ", "department": "Mathematics Department", "position": "Senior Teacher", "specialization": "Algebra", "contact_number": "09181234568", "address": "456 Education St, Manila", "birth_date": "1988-07-22", "blood_type": "O+", "emergency_contact_name": "MARIA DELA CRUZ", "emergency_contact_number": "09171234567"},
    {"employee_id": "EMP-2024-003", "full_name": "ANNA REYES", "department": "English Department", "position": "Master Teacher I", "specialization": "Literature", "contact_number": "09191234569", "address": "789 Academic Ave, Pasig", "birth_date": "1982-11-30", "blood_type": "B+", "emergency_contact_name": "ROBERT REYES", "emergency_contact_number": "09191234500"},
    {"employee_id": "EMP-2024-004", "full_name": "PEDRO GARCIA", "department": "Filipino Department", "position": "Teacher III", "specialization": "Panitikan", "contact_number": "09201234570", "address": "321 School Rd, Makati", "birth_date": "1990-05-18", "blood_type": "AB+", "emergency_contact_name": "JUANA GARCIA", "emergency_contact_number": "09201234500"},
    {"employee_id": "EMP-2024-005", "full_name": "ELENA CRUZ", "department": "Science Department", "position": "Teacher II", "specialization": "Chemistry", "contact_number": "09211234571", "address": "654 Campus Dr, Taguig", "birth_date": "1987-09-25", "blood_type": "A-", "emergency_contact_name": "MARIO CRUZ", "emergency_contact_number": "09211234500"},
    {"employee_id": "EMP-2024-006", "full_name": "JOSE RAMOS", "department": "Social Studies", "position": "Teacher III", "specialization": "History", "contact_number": "09221234572", "address": "987 College St, Caloocan", "birth_date": "1984-12-03", "blood_type": "O-", "emergency_contact_name": "JOSEPHINE RAMOS", "emergency_contact_number": "09221234500"},
    {"employee_id": "EMP-2024-007", "full_name": "CARMEN LOPEZ", "department": "Values Education", "position": "Teacher II", "specialization": "Ethics", "contact_number": "09231234573", "address": "147 University Blvd, Paranaque", "birth_date": "1989-02-14", "blood_type": "B-", "emergency_contact_name": "CARLO LOPEZ", "emergency_contact_number": "09231234500"},
    {"employee_id": "EMP-2024-008", "full_name": "RICARDO TAN", "department": "Physical Education", "position": "Coach", "specialization": "Basketball", "contact_number": "09241234574", "address": "258 Sports Complex, Las Pinas", "birth_date": "1986-08-07", "blood_type": "AB-", "emergency_contact_name": "REGINA TAN", "emergency_contact_number": "09241234500"},
    {"employee_id": "EMP-2024-009", "full_name": "LINDA FERNANDEZ", "department": "Arts Department", "position": "Teacher I", "specialization": "Visual Arts", "contact_number": "09251234575", "address": "369 Creative St, Muntinlupa", "birth_date": "1991-04-20", "blood_type": "A+", "emergency_contact_name": "LUIS FERNANDEZ", "emergency_contact_number": "09251234500"},
    {"employee_id": "EMP-2024-010", "full_name": "MICHAEL ABAD", "department": "Computer Science", "position": "Teacher III", "specialization": "Programming", "contact_number": "09261234576", "address": "741 Tech Park, Pasay", "birth_date": "1983-10-12", "blood_type": "O+", "emergency_contact_name": "MICHELLE ABAD", "emergency_contact_number": "09261234500"},
    {"employee_id": "EMP-2024-011", "full_name": "ROSARIO VILLA", "department": "Mathematics Department", "position": "Teacher II", "specialization": "Geometry", "contact_number": "09271234577", "address": "852 Math Lane, Mandaluyong", "birth_date": "1988-06-28", "blood_type": "B+", "emergency_contact_name": "RENE VILLA", "emergency_contact_number": "09271234500"},
    {"employee_id": "EMP-2024-012", "full_name": "ANTONIO CRUZ", "department": "English Department", "position": "Teacher I", "specialization": "Grammar", "contact_number": "09281234578", "address": "963 Language St, San Juan", "birth_date": "1992-01-09", "blood_type": "A-", "emergency_contact_name": "ANITA CRUZ", "emergency_contact_number": "09281234500"},
    {"employee_id": "EMP-2024-013", "full_name": "TERESA AQUINO", "department": "Science Department", "position": "Teacher II", "specialization": "Biology", "contact_number": "09291234579", "address": "159 Science Ave, Marikina", "birth_date": "1985-11-17", "blood_type": "O-", "emergency_contact_name": "TOMAS AQUINO", "emergency_contact_number": "09291234500"},
    {"employee_id": "EMP-2024-014", "full_name": "FRANCISCO RAMOS", "department": "Music Department", "position": "Teacher III", "specialization": "Vocal Music", "contact_number": "09301234580", "address": "357 Melody Rd, Valenzuela", "birth_date": "1987-03-26", "blood_type": "AB+", "emergency_contact_name": "FRANCES RAMOS", "emergency_contact_number": "09301234500"},
    {"employee_id": "EMP-2024-015", "full_name": "GLORIA SANTOS", "department": "Home Economics", "position": "Teacher II", "specialization": "Cookery", "contact_number": "09311234581", "address": "486 Culinary St, Navotas", "birth_date": "1990-07-04", "blood_type": "B-", "emergency_contact_name": "GERARDO SANTOS", "emergency_contact_number": "09311234500"},
    {"employee_id": "EMP-2024-016", "full_name": "RAMON DIAZ", "department": "Industrial Arts", "position": "Teacher III", "specialization": "Woodworking", "contact_number": "09321234582", "address": "624 Workshop Ave, Malabon", "birth_date": "1984-09-13", "blood_type": "A+", "emergency_contact_name": "RAMONA DIAZ", "emergency_contact_number": "09321234500"},
    {"employee_id": "EMP-2024-017", "full_name": "IMELDA REYES", "department": "Library Services", "position": "Librarian", "specialization": "Library Science", "contact_number": "09331234583", "address": "735 Books St, Pateros", "birth_date": "1986-12-21", "blood_type": "O+", "emergency_contact_name": "IGNACIO REYES", "emergency_contact_number": "09331234500"},
    {"employee_id": "EMP-2024-018", "full_name": "EDUARDO CRUZ", "department": "Guidance Office", "position": "Guidance Counselor", "specialization": "Psychology", "contact_number": "09341234584", "address": "846 Counseling Lane, Taguig", "birth_date": "1989-05-30", "blood_type": "B+", "emergency_contact_name": "EDITHA CRUZ", "emergency_contact_number": "09341234500"},
    {"employee_id": "EMP-2024-019", "full_name": "VICTORIA LOPEZ", "department": "Health Services", "position": "School Nurse", "specialization": "Nursing", "contact_number": "09351234585", "address": "957 Medical Rd, Paranaque", "birth_date": "1987-02-08", "blood_type": "A-", "emergency_contact_name": "VICTOR LOPEZ", "emergency_contact_number": "09351234500"},
    {"employee_id": "EMP-2024-020", "full_name": "ALFREDO TAN", "department": "Science Department", "position": "Laboratory Technician", "specialization": "Laboratory Science", "contact_number": "09361234586", "address": "168 Lab St, Muntinlupa", "birth_date": "1991-08-16", "blood_type": "O-", "emergency_contact_name": "ALICIA TAN", "emergency_contact_number": "09361234500"},
    {"employee_id": "EMP-2024-021", "full_name": "BEATRIZ GARCIA", "department": "Administrative Office", "position": "Registrar", "specialization": "Records Management", "contact_number": "09371234587", "address": "279 Admin Blvd, Pasay", "birth_date": "1983-11-24", "blood_type": "AB+", "emergency_contact_name": "BERNARDO GARCIA", "emergency_contact_number": "09371234500"},
    {"employee_id": "EMP-2024-022", "full_name": "CARLOS VILLA", "department": "Mathematics Department", "position": "Teacher I", "specialization": "Statistics", "contact_number": "09381234588", "address": "381 Data St, Makati", "birth_date": "1993-04-02", "blood_type": "B-", "emergency_contact_name": "CARLA VILLA", "emergency_contact_number": "09381234500"},
    {"employee_id": "EMP-2024-023", "full_name": "DIANA FERNANDEZ", "department": "English Department", "position": "Teacher II", "specialization": "Creative Writing", "contact_number": "09391234589", "address": "492 Writers Ave, Manila", "birth_date": "1988-07-11", "blood_type": "A+", "emergency_contact_name": "DANIEL FERNANDEZ", "emergency_contact_number": "09391234500"},
    {"employee_id": "EMP-2024-024", "full_name": "ERNESTO AQUINO", "department": "Physical Education", "position": "Teacher II", "specialization": "Volleyball", "contact_number": "09401234590", "address": "513 Sports Lane, Quezon City", "birth_date": "1986-10-19", "blood_type": "O+", "emergency_contact_name": "ERLINDA AQUINO", "emergency_contact_number": "09401234500"},
    {"employee_id": "EMP-2024-025", "full_name": "FELICIA RAMOS", "department": "Arts Department", "position": "Teacher II", "specialization": "Music Theory", "contact_number": "09411234591", "address": "624 Harmony Rd, Caloocan", "birth_date": "1990-01-27", "blood_type": "B+", "emergency_contact_name": "FELIPE RAMOS", "emergency_contact_number": "09411234500"},
    {"employee_id": "EMP-2024-026", "full_name": "GABRIEL DIAZ", "department": "Science Department", "position": "Teacher I", "specialization": "Earth Science", "contact_number": "09421234592", "address": "735 Geology St, Pasig", "birth_date": "1992-06-05", "blood_type": "A-", "emergency_contact_name": "GABRIELA DIAZ", "emergency_contact_number": "09421234500"},
    {"employee_id": "EMP-2024-027", "full_name": "HELENA SANTOS", "department": "Filipino Department", "position": "Teacher II", "specialization": "Gramatika", "contact_number": "09431234593", "address": "846 Wika Ave, Las Pinas", "birth_date": "1985-09-14", "blood_type": "O-", "emergency_contact_name": "HERMINIO SANTOS", "emergency_contact_number": "09431234500"},
    {"employee_id": "EMP-2024-028", "full_name": "IGNACIO CRUZ", "department": "Social Studies", "position": "Teacher I", "specialization": "Economics", "contact_number": "09441234594", "address": "957 Commerce Blvd, Valenzuela", "birth_date": "1991-12-22", "blood_type": "AB+", "emergency_contact_name": "IRENE CRUZ", "emergency_contact_number": "09441234500"},
    {"employee_id": "EMP-2024-029", "full_name": "JULIANA REYES", "department": "Computer Science", "position": "Teacher II", "specialization": "Web Design", "contact_number": "09451234595", "address": "168 Digital St, Navotas", "birth_date": "1987-03-01", "blood_type": "B-", "emergency_contact_name": "JULIUS REYES", "emergency_contact_number": "09451234500"},
    {"employee_id": "EMP-2024-030", "full_name": "KRISTIAN TAN", "department": "Mathematics Department", "position": "Teacher III", "specialization": "Trigonometry", "contact_number": "09461234596", "address": "279 Angles Ave, Malabon", "birth_date": "1984-06-10", "blood_type": "A+", "emergency_contact_name": "KRISTINA TAN", "emergency_contact_number": "09461234500"},
    {"employee_id": "EMP-2024-031", "full_name": "LUCIA LOPEZ", "department": "English Department", "position": "Teacher III", "specialization": "Journalism", "contact_number": "09471234597", "address": "381 Press Rd, Marikina", "birth_date": "1988-09-18", "blood_type": "O+", "emergency_contact_name": "LUCIO LOPEZ", "emergency_contact_number": "09471234500"},
    {"employee_id": "EMP-2024-032", "full_name": "MANUEL GARCIA", "department": "Physical Education", "position": "Teacher I", "specialization": "Swimming", "contact_number": "09481234598", "address": "492 Pool Lane, San Juan", "birth_date": "1993-12-26", "blood_type": "B+", "emergency_contact_name": "MANUELA GARCIA", "emergency_contact_number": "09481234500"},
    {"employee_id": "EMP-2024-033", "full_name": "NORA VILLA", "department": "Home Economics", "position": "Teacher I", "specialization": "Sewing", "contact_number": "09491234599", "address": "513 Fashion St, Mandaluyong", "birth_date": "1989-05-04", "blood_type": "A-", "emergency_contact_name": "NESTOR VILLA", "emergency_contact_number": "09491234500"},
    {"employee_id": "EMP-2024-034", "full_name": "OSCAR FERNANDEZ", "department": "Industrial Arts", "position": "Teacher II", "specialization": "Electronics", "contact_number": "09501234600", "address": "624 Circuit Ave, Pateros", "birth_date": "1986-08-13", "blood_type": "O-", "emergency_contact_name": "OLIVIA FERNANDEZ", "emergency_contact_number": "09501234600"},
    {"employee_id": "EMP-2024-035", "full_name": "PATRICIA AQUINO", "department": "Science Department", "position": "Teacher III", "specialization": "Environmental Science", "contact_number": "09511234601", "address": "735 Green Blvd, Taguig", "birth_date": "1984-11-21", "blood_type": "AB+", "emergency_contact_name": "PATRICIO AQUINO", "emergency_contact_number": "09511234500"},
    {"employee_id": "EMP-2024-036", "full_name": "QUINN RAMOS", "department": "Mathematics Department", "position": "Teacher II", "specialization": "Calculus", "contact_number": "09521234602", "address": "846 Derivative St, Paranaque", "birth_date": "1990-02-28", "blood_type": "B-", "emergency_contact_name": "QUENTIN RAMOS", "emergency_contact_number": "09521234500"},
    {"employee_id": "EMP-2024-037", "full_name": "REGINA DIAZ", "department": "English Department", "position": "Teacher I", "specialization": "Public Speaking", "contact_number": "09531234603", "address": "957 Oratory Rd, Muntinlupa", "birth_date": "1992-07-07", "blood_type": "A+", "emergency_contact_name": "REGINALD DIAZ", "emergency_contact_number": "09531234500"},
    {"employee_id": "EMP-2024-038", "full_name": "SALVADOR SANTOS", "department": "Social Studies", "position": "Teacher II", "specialization": "Political Science", "contact_number": "09541234604", "address": "168 Government Ave, Pasay", "birth_date": "1987-10-15", "blood_type": "O+", "emergency_contact_name": "SALVACION SANTOS", "emergency_contact_number": "09541234500"},
    {"employee_id": "EMP-2024-039", "full_name": "THELMA CRUZ", "department": "Filipino Department", "position": "Teacher I", "specialization": "Pagsasalin", "contact_number": "09551234605", "address": "279 Translation Lane, Makati", "birth_date": "1991-01-23", "blood_type": "B+", "emergency_contact_name": "TEODORO CRUZ", "emergency_contact_number": "09551234500"},
    {"employee_id": "EMP-2024-040", "full_name": "ULYSSES REYES", "department": "Computer Science", "position": "Teacher I", "specialization": "Database Management", "contact_number": "09561234606", "address": "381 SQL St, Manila", "birth_date": "1988-04-01", "blood_type": "A-", "emergency_contact_name": "URSULA REYES", "emergency_contact_number": "09561234500"},
    {"employee_id": "EMP-2024-041", "full_name": "VERONICA TAN", "department": "Arts Department", "position": "Teacher III", "specialization": "Drama", "contact_number": "09571234607", "address": "492 Theater Rd, Quezon City", "birth_date": "1985-07-10", "blood_type": "O-", "emergency_contact_name": "VALENTIN TAN", "emergency_contact_number": "09571234500"},
    {"employee_id": "EMP-2024-042", "full_name": "WILLIAM LOPEZ", "department": "Physical Education", "position": "Teacher III", "specialization": "Track and Field", "contact_number": "09581234608", "address": "513 Sprint Ave, Caloocan", "birth_date": "1989-10-18", "blood_type": "AB+", "emergency_contact_name": "WILMA LOPEZ", "emergency_contact_number": "09581234500"},
    {"employee_id": "EMP-2024-043", "full_name": "XIMENA GARCIA", "department": "Science Department", "position": "Teacher II", "specialization": "Astronomy", "contact_number": "09591234609", "address": "624 Cosmos Blvd, Pasig", "birth_date": "1986-01-26", "blood_type": "B-", "emergency_contact_name": "XAVIER GARCIA", "emergency_contact_number": "09591234500"},
    {"employee_id": "EMP-2024-044", "full_name": "YOLANDA VILLA", "department": "Mathematics Department", "position": "Teacher I", "specialization": "Logic", "contact_number": "09601234610", "address": "735 Reasoning St, Las Pinas", "birth_date": "1993-05-05", "blood_type": "A+", "emergency_contact_name": "YUSEF VILLA", "emergency_contact_number": "09601234500"},
    {"employee_id": "EMP-2024-045", "full_name": "ZACHARY FERNANDEZ", "department": "English Department", "position": "Teacher II", "specialization": "Debate", "contact_number": "09611234611", "address": "846 Argument Lane, Valenzuela", "birth_date": "1987-08-14", "blood_type": "O+", "emergency_contact_name": "ZENAIDA FERNANDEZ", "emergency_contact_number": "09611234500"},
    {"employee_id": "EMP-2024-046", "full_name": "ANDREA AQUINO", "department": "Values Education", "position": "Teacher I", "specialization": "Philosophy", "contact_number": "09621234612", "address": "957 Ethics Ave, Navotas", "birth_date": "1991-11-22", "blood_type": "B+", "emergency_contact_name": "ANDRES AQUINO", "emergency_contact_number": "09621234500"},
    {"employee_id": "EMP-2024-047", "full_name": "BENJAMIN RAMOS", "department": "Computer Science", "position": "Teacher III", "specialization": "Cybersecurity", "contact_number": "09631234613", "address": "168 Security Rd, Malabon", "birth_date": "1984-02-29", "blood_type": "A-", "emergency_contact_name": "BENILDA RAMOS", "emergency_contact_number": "09631234500"},
    {"employee_id": "EMP-2024-048", "full_name": "CECILIA DIAZ", "department": "Home Economics", "position": "Teacher III", "specialization": "Food Technology", "contact_number": "09641234614", "address": "279 Nutrition St, Marikina", "birth_date": "1988-06-08", "blood_type": "O-", "emergency_contact_name": "CECILIO DIAZ", "emergency_contact_number": "09641234500"},
    {"employee_id": "EMP-2024-049", "full_name": "DOMINGO SANTOS", "department": "Industrial Arts", "position": "Teacher I", "specialization": "Automotive", "contact_number": "09651234615", "address": "381 Mechanic Blvd, San Juan", "birth_date": "1992-09-16", "blood_type": "AB+", "emergency_contact_name": "DOMINGA SANTOS", "emergency_contact_number": "09651234500"},
    {"employee_id": "EMP-2024-050", "full_name": "ESPERANZA CRUZ", "department": "Music Department", "position": "Teacher II", "specialization": "Piano", "contact_number": "09661234616", "address": "492 Keyboard Ave, Mandaluyong", "birth_date": "1986-12-24", "blood_type": "B-", "emergency_contact_name": "ESTEBAN CRUZ", "emergency_contact_number": "09661234500"},

    # 25 new complete mock professors to complete 75
    {"employee_id": "EMP-2024-051", "full_name": "DR. ALEXANDER GRAHAM", "department": "Science Department", "position": "Professor", "specialization": "Electromagnetism", "contact_number": "09771230051", "address": "111 Innovation Way, Quezon City", "birth_date": "1978-02-11", "blood_type": "O+", "emergency_contact_name": "MABEL GRAHAM", "emergency_contact_number": "09771230151"},
    {"employee_id": "EMP-2024-052", "full_name": "PROF. BEATRICE CHEN", "department": "Mathematics Department", "position": "Professor", "specialization": "Topology", "contact_number": "09771230052", "address": "222 Helix Rd, Manila", "birth_date": "1980-04-18", "blood_type": "A+", "emergency_contact_name": "CHARLES CHEN", "emergency_contact_number": "09771230152"},
    {"employee_id": "EMP-2024-053", "full_name": "DR. CHARLES DARWIN", "department": "Science Department", "position": "Professor", "specialization": "Evolutionary Biology", "contact_number": "09771230053", "address": "333 Galapagos Ave, Pasig", "birth_date": "1975-09-22", "blood_type": "B+", "emergency_contact_name": "EMMA DARWIN", "emergency_contact_number": "09771230153"},
    {"employee_id": "EMP-2024-054", "full_name": "PROF. DIANA PRINCE", "department": "Social Studies", "position": "Associate Professor", "specialization": "Ancient History", "contact_number": "09771230054", "address": "444 Themyscira Blvd, Makati", "birth_date": "1983-11-05", "blood_type": "AB+", "emergency_contact_name": "STEVE TREVOR", "emergency_contact_number": "09771230154"},
    {"employee_id": "EMP-2024-055", "full_name": "DR. EDWIN HUBBLE", "department": "Science Department", "position": "Professor", "specialization": "Astrophysics", "contact_number": "09771230055", "address": "555 Nebula Lane, Taguig", "birth_date": "1982-12-25", "blood_type": "O-", "emergency_contact_name": "GRACE HUBBLE", "emergency_contact_number": "09771230155"},
    {"employee_id": "EMP-2024-056", "full_name": "PROF. FIONA GALLAGHER", "department": "English Department", "position": "Assistant Professor", "specialization": "Creative Writing", "contact_number": "09771230056", "address": "666 Literary Rd, Caloocan", "birth_date": "1989-08-12", "blood_type": "A-", "emergency_contact_name": "LIP GALLAGHER", "emergency_contact_number": "09771230156"},
    {"employee_id": "EMP-2024-057", "full_name": "DR. GREGORY HOUSE", "department": "Health Services", "position": "Professor & Consultant", "specialization": "Diagnostic Medicine", "contact_number": "09771230057", "address": "777 Clinic Ave, Paranaque", "birth_date": "1974-06-11", "blood_type": "AB-", "emergency_contact_name": "JAMES WILSON", "emergency_contact_number": "09771230157"},
    {"employee_id": "EMP-2024-058", "full_name": "PROF. HAROLD FINCH", "department": "Computer Science", "position": "Professor", "specialization": "Artificial Intelligence", "contact_number": "09771230058", "address": "888 Algorithm St, Las Pinas", "birth_date": "1971-03-30", "blood_type": "O+", "emergency_contact_name": "JOHN REESE", "emergency_contact_number": "09771230158"},
    {"employee_id": "EMP-2024-059", "full_name": "DR. IRENE ADLER", "department": "Values Education", "position": "Associate Professor", "specialization": "Applied Philosophy", "contact_number": "09771230059", "address": "999 Logic Loop, Muntinlupa", "birth_date": "1985-05-01", "blood_type": "B-", "emergency_contact_name": "SHERLOCK HOLMES", "emergency_contact_number": "09771230159"},
    {"employee_id": "EMP-2024-060", "full_name": "PROF. JOHN VON NEUMANN", "department": "Computer Science", "position": "Professor", "specialization": "Game Theory & Architecture", "contact_number": "09771230060", "address": "124 Binary Way, Pasay", "birth_date": "1970-12-03", "blood_type": "A+", "emergency_contact_name": "KLARA VON NEUMANN", "emergency_contact_number": "09771230160"},
    {"employee_id": "EMP-2024-061", "full_name": "DR. KATHERINE JOHNSON", "department": "Mathematics Department", "position": "Professor", "specialization": "Orbital Mechanics", "contact_number": "09771230061", "address": "235 Trajectory Dr, Mandaluyong", "birth_date": "1981-08-26", "blood_type": "O+", "emergency_contact_name": "JAMES JOHNSON", "emergency_contact_number": "09771230161"},
    {"employee_id": "EMP-2024-062", "full_name": "PROF. LINUS PAULING", "department": "Science Department", "position": "Professor", "specialization": "Quantum Chemistry", "contact_number": "09771230062", "address": "346 Valence Rd, San Juan", "birth_date": "1976-02-28", "blood_type": "B+", "emergency_contact_name": "AVA PAULING", "emergency_contact_number": "09771230162"},
    {"employee_id": "EMP-2024-063", "full_name": "DR. MARIE CURIE", "department": "Science Department", "position": "Professor", "specialization": "Radiochemistry", "contact_number": "09771230063", "address": "457 Polonium Ave, Marikina", "birth_date": "1977-11-07", "blood_type": "AB+", "emergency_contact_name": "PIERRE CURIE", "emergency_contact_number": "09771230163"},
    {"employee_id": "EMP-2024-064", "full_name": "PROF. NIKOLA TESLA", "department": "Industrial Arts", "position": "Associate Professor", "specialization": "AC Circuits & Robotics", "contact_number": "09771230064", "address": "568 Wardenclyffe Rd, Valenzuela", "birth_date": "1980-07-10", "blood_type": "A-", "emergency_contact_name": "MILUTIN TESLA", "emergency_contact_number": "09771230164"},
    {"employee_id": "EMP-2024-065", "full_name": "DR. OPAL COB", "department": "Home Economics", "position": "Assistant Professor", "specialization": "Nutrition Sciences", "contact_number": "09771230065", "address": "679 Recipe Rd, Navotas", "birth_date": "1988-04-09", "blood_type": "O-", "emergency_contact_name": "BASIL COB", "emergency_contact_number": "09771230165"},
    {"employee_id": "EMP-2024-066", "full_name": "PROF. PETER PARKER", "department": "Arts Department", "position": "Instructor", "specialization": "Photojournalism", "contact_number": "09771230066", "address": "790 Web Ave, Malabon", "birth_date": "1994-10-14", "blood_type": "O+", "emergency_contact_name": "MAY PARKER", "emergency_contact_number": "09771230166"},
    {"employee_id": "EMP-2024-067", "full_name": "DR. QUENTIN TARANTINO", "department": "Arts Department", "position": "Professor", "specialization": "Cinema & Film Studies", "contact_number": "09771230067", "address": "901 Hollywood Way, Pateros", "birth_date": "1973-03-27", "blood_type": "B-", "emergency_contact_name": "CONNIE TARANTINO", "emergency_contact_number": "09771230167"},
    {"employee_id": "EMP-2024-068", "full_name": "PROF. RICHARD FEYNMAN", "department": "Science Department", "position": "Professor", "specialization": "Quantum Electrodynamics", "contact_number": "09771230068", "address": "135 Nanotech Ave, Taguig", "birth_date": "1978-05-11", "blood_type": "A+", "emergency_contact_name": "ARLINE FEYNMAN", "emergency_contact_number": "09771230168"},
    {"employee_id": "EMP-2024-069", "full_name": "DR. STEPHEN HAWKING", "department": "Science Department", "position": "Professor", "specialization": "Cosmology", "contact_number": "09771230069", "address": "246 Singularity Lane, Paranaque", "birth_date": "1972-01-08", "blood_type": "AB-", "emergency_contact_name": "JANE HAWKING", "emergency_contact_number": "09771230169"},
    {"employee_id": "EMP-2024-070", "full_name": "PROF. TIM BERNERS-LEE", "department": "Computer Science", "position": "Professor", "specialization": "Web Technologies", "contact_number": "09771230070", "address": "357 Protocol St, Muntinlupa", "birth_date": "1975-06-08", "blood_type": "O+", "emergency_contact_name": "ROSEMARY BERNERS-LEE", "emergency_contact_number": "09771230170"},
    {"employee_id": "EMP-2024-071", "full_name": "DR. URSULA FRANKLIN", "department": "Industrial Arts", "position": "Professor", "specialization": "Metallurgy & Tech History", "contact_number": "09771230071", "address": "468 Alloy Rd, Pasay", "birth_date": "1971-09-16", "blood_type": "A-", "emergency_contact_name": "ALAN FRANKLIN", "emergency_contact_number": "09771230171"},
    {"employee_id": "EMP-2024-072", "full_name": "PROF. VIRGINIA WOOLF", "department": "English Department", "position": "Associate Professor", "specialization": "Modernist Literature", "contact_number": "09771230072", "address": "579 Stream Lane, Makati", "birth_date": "1982-01-25", "blood_type": "B-", "emergency_contact_name": "LEONARD WOOLF", "emergency_contact_number": "09771230172"},
    {"employee_id": "EMP-2024-073", "full_name": "DR. WERNER HEISENBERG", "department": "Science Department", "position": "Professor", "specialization": "Quantum Mechanics", "contact_number": "09771230073", "address": "690 Matrix St, Manila", "birth_date": "1981-12-05", "blood_type": "AB+", "emergency_contact_name": "ELISABETH HEISENBERG", "emergency_contact_number": "09771230173"},
    {"employee_id": "EMP-2024-074", "full_name": "PROF. XAVIER CHARLES", "department": "Guidance Office", "position": "Guidance Director", "specialization": "Special Education Needs", "contact_number": "09771230074", "address": "801 Cerebro Blvd, Quezon City", "birth_date": "1972-07-13", "blood_type": "O-", "emergency_contact_name": "ERIK LEHNSHERR", "emergency_contact_number": "09771230174"},
    {"employee_id": "EMP-2024-075", "full_name": "DR. YVONNE BARR", "department": "Science Department", "position": "Associate Professor", "specialization": "Virology", "contact_number": "09771230075", "address": "912 Epstein Dr, Caloocan", "birth_date": "1982-03-11", "blood_type": "A+", "emergency_contact_name": "MICHAEL BARR", "emergency_contact_number": "09771230175"}
]

def seed_teachers():
    print("🌱 Starting complete teacher seeding script...")
    print(f"Seeding a total of {len(TEACHERS_DATA)} records...")
    
    # We will use INSERT ... ON DUPLICATE KEY UPDATE to make this fully idempotent
    insert_query = """
        INSERT INTO teachers (
            employee_id, full_name, department, position, specialization,
            contact_number, address, birth_date, blood_type,
            emergency_contact_name, emergency_contact_number, hire_date, employment_status
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
            full_name = VALUES(full_name),
            department = VALUES(department),
            position = VALUES(position),
            specialization = VALUES(specialization),
            contact_number = VALUES(contact_number),
            address = VALUES(address),
            birth_date = VALUES(birth_date),
            blood_type = VALUES(blood_type),
            emergency_contact_name = VALUES(emergency_contact_name),
            emergency_contact_number = VALUES(emergency_contact_number),
            employment_status = VALUES(employment_status)
    """
    
    inserted_count = 0
    
    try:
        with db_manager.transaction() as conn:
            cursor = conn.cursor()
            for teacher in TEACHERS_DATA:
                params = (
                    teacher["employee_id"],
                    teacher["full_name"],
                    teacher["department"],
                    teacher["position"],
                    teacher["specialization"],
                    teacher["contact_number"],
                    teacher["address"],
                    teacher["birth_date"],
                    teacher["blood_type"],
                    teacher["emergency_contact_name"],
                    teacher["emergency_contact_number"],
                    date(2024, 1, 1), # Default hire date
                    "active"
                )
                cursor.execute(insert_query, params)
                inserted_count += 1
            cursor.close()
        print(f"✅ Successfully seeded {inserted_count} teachers!")
        return True
    except Exception as e:
        print(f"❌ Error seeding teachers: {e}", file=sys.stderr)
        return False

if __name__ == "__main__":
    success = seed_teachers()
    sys.exit(0 if success else 1)
